### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Kolaer** [Askhat73/bulletinboard#1]
- [x] StandartModel лучше вынести из users приложения (например создать core и перенести туда). StandartModel  не связан непосредсвенно с пользователями и это немного путает
- [x] MoneyField туда же
- [x] Проект не запускается с нуля (в репозитории нет Pipfile.lock). Нужно добавить. Весь смысл подобных файлов в том, чтобы можно было собрать проект с точно такими же зависимостями (учитывая зависомости зависимостей и так далее). Если его игнорировать, то эта возможность теряется 

В целом написано очень хорошо) Продолжай в том же духе

**Comment by arifullov** [comment]
Поправил
